// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcdkvxorsyqsrxolxoni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjZGt2eG9yc3lxc3J4b2x4b25pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzM2NjksImV4cCI6MjA2ODk0OTY2OX0.wRk17zh5W1iI_3kGVF73GeZVPB6VPppzqhYqaxtjnmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});